Repository eclipse-sirius/sirius-desktop, pull requests merged in 2024-04, with the labels that each got.

#347 [346] Support "Paste Style" when source and target are of different types
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/AbstractSiriusFormatDataManager.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/SiriusStyleApplicator.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.aird
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.ecore
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/My.odesign
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
Labels: type: enhancement, component: diagrams

#355 [346] Update paste style documentation
  plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.html
  plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.textile
Labels: component: doc

#361 [152] Fix sequence test by updating label color
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/HeaderSequenceDiagramTests.java
Labels: component: sequences, component: diagrams

#383 [362] Fix the bug in the refresh of the layer tooltip
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/AbstractMenuContributionItem.java
Labels: type: bug

#381 [doc] Fix broken anchor link in Sirius Specifier Manual
  plugins/org.eclipse.sirius.eef.adapters/doc/textile/viewpoint-eef-toc.xml
Labels: component: doc
