Repository eclipse-sirius/sirius-desktop, pull requests merged in 2024-01, with the labels that each got.

#93 [145] Arrange linked border nodes when updating their container
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/api/view/SiriusLayoutDataManager.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataManagerImpl.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutCommand.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutHandler.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/layout/provider/DefaultLayoutProvider.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/DOperationHistoryListener.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java
  plugins/org.eclipse.sirius.doc/doc/Release_Notes.html
  plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.aird
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.ecore
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.odesign
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LinkedBorderNodeLocationTest.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
Labels: type: enhancement, component: diagrams

#228 [153] Fix exception in Layout Children action
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java
Labels: type: bug, component: diagrams

#229 [65] Fix GMFBoundsUpdater
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/GMFBoundsUpdater.java
Labels: component: diagrams

#243 [144][test] Fix an NPE in the unreliable collab tests
  plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
Labels: type: bug

#231 [205] Add tool to copy-paste style for any diagram elements
  plugins/org.eclipse.sirius.diagram.ui/plugin.properties
  plugins/org.eclipse.sirius.diagram.ui/plugin.xml
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/providers/SiriusContributionItemProvider.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/part/SiriusDiagramActionBarContributor.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/editor/tabbar/AbstractTabbarContributor.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/SiriusStyleClipboard.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/ui/actions/ActionIds.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/SiriusCopyAppearancePropertiesAction.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/CopyFormatAction.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/commands/CopyStyleCommand.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/commands/PasteStyleCommandProvider.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/TabbarFillerWithContributions.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/PasteFormatMenuManager.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/TabbarPasteFormatMenuManager.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/contributions/TabbarContributionFactory.java
  plugins/org.eclipse.sirius.diagram.ui/src/org/eclipse/sirius/diagram/ui/provider/Messages.java
  plugins/org.eclipse.sirius.doc/doc/Release_Notes.html
  plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
  plugins/org.eclipse.sirius.doc/doc/i18n_changes.html
  plugins/org.eclipse.sirius.doc/doc/i18n_changes.textile
  plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.html
  plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.textile
  plugins/org.eclipse.sirius.doc/doc/user/diagrams/images/diagram_editor_paste_style.png
  plugins/org.eclipse.sirius.ecore.extender/src/org/eclipse/sirius/ecore/extender/business/api/permission/ISimpleAuthorityListener.java
  plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.aird
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.ecore
  plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/My.odesign
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SetStyleToWorkspaceImageTests.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/CopyAppearanceActionTest.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/TabbarContributorExtensionTest.java
  plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/TabbarContributorSample.java
Labels: type: enhancement, component: diagrams

#247 [releng] Remove global 1 hour timeout
  Jenkinsfile
Labels: component: releng

#248 [173] Change pin/unpin button activation policy with multiple selection
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
Labels: type: enhancement, component: diagrams

#250 [205] Fix bug in paste style action (missing removeAuthorityListener)
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java
  plugins/org.eclipse.sirius.ecore.extender/src/org/eclipse/sirius/ecore/extender/business/internal/permission/AbstractPermissionAuthority.java
Labels: type: bug, component: diagrams
