Repository eclipse-sirius/sirius-desktop, pull requests merged in 2024-12, with the labels that each got.

#525 [fix] Fix potential NPEs
  plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/part/ObservationPointEditPart.java
  plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/CanonicalSynchronizerResult.java
Labels: type: bug, component: sequences, component: diagrams

#526 [508] Prevents NPE and index out of bound with Debug view.
  plugins/org.eclipse.sirius.debug/src/org/eclipse/sirius/api/debug/AbstractDebugView.java
Labels: type: bug, component: core

#533 [532] Fix potential MetaClassNotFoundException in Sequence diagram
  plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/internal/tool/command/builders/MessageCreationCommandBuilder.java
Labels: type: bug, component: sequences

#539 [536] Fix ISEComplexeMoveValidator re-initialization
  plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/validator/ISEComplexMoveValidator.java
Labels: component: sequences
